#!/usr/bin/env bash
# log_step.sh — append a timestamped, git-SHA-stamped event line to a per-step markdown log.
#
# Usage:
#   scripts/log_step.sh <step_id> <event> [key=val ...]
#
# Example:
#   scripts/log_step.sh 01-data-curation start
#   scripts/log_step.sh 01-data-curation artifact path=docs/finetune/data/run_failed_735.csv n_rows=735
#   scripts/log_step.sh 01-data-curation end status=done
#
# Writes to docs/finetune/<step_id>.md. Creates the file with a `# Step <step_id>` header on first call.

set -euo pipefail

if [ "$#" -lt 2 ]; then
  echo "usage: $0 <step_id> <event> [key=val ...]" >&2
  exit 2
fi

STEP_ID="$1"; shift
EVENT="$1"; shift

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOG="$REPO_ROOT/docs/finetune/${STEP_ID}.md"
TS="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
# Dual SHA: outer repo (docs/configs/scripts) + inner limo/ repo (LIMO code).
OUTER_SHA="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo 'no-git')"
INNER_SHA="$(git -C "$REPO_ROOT/limo" rev-parse --short HEAD 2>/dev/null || echo 'no-inner-git')"
GIT_SHA="${OUTER_SHA}+${INNER_SHA}"
HOST="$(uname -n | tr -d '[:space:]')"

# Initialize the log file with a header on first write.
if [ ! -f "$LOG" ]; then
  printf '# Step %s\n\nGenerated by `scripts/log_step.sh`. Append-only.\n\n## Event log\n\n' "$STEP_ID" > "$LOG"
fi

# Build the kv tail.
KV=""
for arg in "$@"; do
  KV="$KV $arg"
done

# Append one event line. Use single-process append; on macOS this is atomic for short writes.
printf -- '- `%s` [%s] (%s) **%s**%s\n' "$TS" "$GIT_SHA" "$HOST" "$EVENT" "$KV" >> "$LOG"
