#!/usr/bin/env bash
# log_step.sh — append a timestamped, git-SHA-stamped event line to a per-step markdown log.
#
# Usage:
#   scripts/log_step.sh <step_id> <event> [key=val ...]
#
# Example:
#   scripts/log_step.sh 01-data-curation start
#   scripts/log_step.sh 01-data-curation artifact path=docs/finetune/data/run_failed_735.csv n_rows=735
#   scripts/log_step.sh 01-data-curation end status=done
#
# Writes to docs/finetune/<step_id>.md. Creates the file with a `# Step <step_id>` header on first call.

set -euo pipefail

if [ "$#" -lt 2 ]; then
  echo "usage: $0 <step_id> <event> [key=val ...]" >&2
  exit 2
fi

STEP_ID="$1"; shift
EVENT="$1"; shift

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOG="$REPO_ROOT/docs/finetune/${STEP_ID}.md"
LOCK="${LOG}.lock"
TS="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
# Dual SHA: outer repo (docs/configs/scripts) + inner limo/ repo (LIMO code).
OUTER_SHA="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo 'no-git')"
INNER_SHA="$(git -C "$REPO_ROOT/limo" rev-parse --short HEAD 2>/dev/null || echo 'no-inner-git')"
GIT_SHA="${OUTER_SHA}+${INNER_SHA}"
HOST="$(uname -n | tr -d '[:space:]')"

mkdir -p "$(dirname "$LOG")"

# Portable mkdir-lock to serialize first-write header init + append across concurrent processes.
# Spins up to ~20s then proceeds anyway (logs are nice-to-have, not gating).
ACQUIRED=0
for _ in $(seq 1 200); do
  if mkdir "$LOCK" 2>/dev/null; then
    ACQUIRED=1
    trap 'rmdir "$LOCK" 2>/dev/null || true' EXIT
    break
  fi
  sleep 0.1
done

# Initialize the log file with a header on first write (now serialized).
if [ ! -f "$LOG" ]; then
  printf '# Step %s\n\nGenerated by `scripts/log_step.sh`. Append-only.\n\n## Event log\n\n' "$STEP_ID" > "$LOG"
fi

# Build the kv tail.
KV=""
for arg in "$@"; do
  KV="$KV $arg"
done

# Append one event line under the lock.
printf -- '- `%s` [%s] (%s) **%s**%s\n' "$TS" "$GIT_SHA" "$HOST" "$EVENT" "$KV" >> "$LOG"

if [ "$ACQUIRED" = "1" ]; then
  rmdir "$LOCK" 2>/dev/null || true
  trap - EXIT
fi
